name: Déploiement de parcours_r_module_datavisualisation

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy-bookdown:
    name: Build and bookdown
    uses: MTES-MCT/parcours-r/.github/workflows/bookdown-build-and-deploy.yml@master
    with:
      r_version: '4.2.2'
  
