name: Image docker parcours_r_module_datavisualisation

on:
  push:
    branches:
      - main
      - master
      - dev
    paths:
      - .github/workflows/rstudio-image-build.yml
      - Dockerfile
      - DESCRIPTION
      
  pull_request:
    types: [opened, synchronize]
    branches: [main, master, dev]
    paths:
      - .github/workflows/rstudio-image-build.yml
      - Dockerfile
      - DESCRIPTION
      
  workflow_dispatch:

jobs:
  build-rstudio-image:
    steps: 
      - uses: MTES-MCT/parcours-r/.github/workflows/rstudio-image-build.yml@master
      - name: Reaparation bug lien gganimate
        run: |
          download.file(url = "https://raw.githubusercontent.com/MTES-MCT/savoirfR/master/vignettes/mod5_exo6_solution-1.gif", 
              destfile = "_book/Valorisation-des-données_files/figure-html/mod5_exo6_solution-192-1.gif")
          download.file(url = "https://raw.githubusercontent.com/MTES-MCT/savoirfR/master/vignettes/mod5_exo6_solution-1.gif", 
              destfile = "_book/Valorisation-des-données_files/figure-html/mod5_exo6_solution-1.gif")
        shell: Rscript {0}
